package com.silicolife.textmining.machinelearning.biotml.core.interfaces;

import java.util.List;
import java.util.Map;
import java.util.Set;

import com.silicolife.textmining.machinelearning.biotml.core.exception.BioTMLException;

/**
 * 
 * Feature generator module interface.
 * Each class that implements this interface will be loaded by a manager.
 * 
 * @since 1.0.0
 * @author Ruben Rodrigues ({@code rrodrigues@silicolife.com})
 */
public interface IBioTMLFeatureGenerator {
	
	/**
	 * 
	 * Method that get the feature names that could be generated by this module.
	 * 
	 * @return Set of feature names.
	 */
	public Set<String> getUIDs();
	
	/**
	 * 
	 * Method that get a map that stores the info of each feature that could be generated by this module.
	 * 
	 * @return Set of feature names.
	 */
	public Map<String, String> getUIDInfos();
	
	/**
	 * 
	 * Method that get a list of recommended UID's that could induce a better model estimation. 
	 * 
	 * @return String list of recomended UID's.
	 */
	public Set<String> getRecomendedUIDs();
	
	/**
	 * 
	 * Method that executes the feature generator regarding the configurator for a list of tokens that belongs to a sentence or document.
	 * 
	 * @param tokens - List of token strings.
	 * @param configuration - Feature generation configurator ({@link IBioTMLFeatureGeneratorConfigurator}).
	 * @return Generated feature colum for all tokens ({@link IBioTMLFeatureColumns}).
	 * @throws BioTMLException
	 */
	public IBioTMLFeatureColumns getFeatureColumns(List<String>tokens,IBioTMLFeatureGeneratorConfigurator configuration) throws BioTMLException;
	
	/**
	 * 
	 * Method that cleans the allocated memory of this module.
	 * 
	 */
	public void cleanMemory();
	
}