package com.silicolife.textmining.machinelearning.biotml.core.interfaces;

import java.util.List;
import java.util.Map;
import java.util.Set;

import com.silicolife.textmining.machinelearning.biotml.core.exception.BioTMLException;

/**
 * 
 * Feature generator module interface.
 * Each class that implements this interface will be loaded by a manager.
 * 
 * @since 1.0.0
 * @author Ruben Rodrigues ({@code rrodrigues@silicolife.com})
 */
public interface IBioTMLFeatureGenerator {
	
	/**
	 * 
	 * Method that get the NER feature names that could be generated by this module.
	 * 
	 * @return Set of NER feature names.
	 */
	public Set<String> getNERFeatureIds();
	
	/**
	 * 
	 * Method that get a map that stores the info of each NER feature that could be generated by this module.
	 * 
	 * @return Set of NER feature names.
	 */
	public Map<String, String> getNERFeatureIdsInfos();
	
	/**
	 * 
	 * Method that get a list of recommended NER feature Ids that could induce a better model estimation. 
	 * 
	 * @return String list of recomended NER feature Ids.
	 */
	public Set<String> getRecomendedNERFeatureIds();
	
	/**
	 * 
	 * Method that get the RE feature names that could be generated by this module.
	 * 
	 * @return Set of RE feature names.
	 */
	public Set<String> getREFeatureIds();
	
	/**
	 * 
	 * Method that get a map that stores the info of each RE feature that could be generated by this module.
	 * 
	 * @return Set of RE feature names.
	 */
	public Map<String, String> getREFeatureIdsInfos();
	
	/**
	 * 
	 * Method that get a list of recommended RE feature Ids that could induce a better model estimation. 
	 * 
	 * @return String list of recomended RE feature Ids.
	 */
	public Set<String> getRecomendedREFeatureIds();
	
	/**
	 * 
	 * Method that executes the feature generator regarding the configurator for a list of tokens that belongs to a sentence or document.
	 * 
	 * @param tokens - List of {@link  IBioTMLToken}.
	 * @param configuration - Feature generation configurator ({@link IBioTMLFeatureGeneratorConfigurator}).
	 * @return Generated feature colum for all tokens ({@link IBioTMLFeatureColumns}).
	 * @throws BioTMLException
	 */
	public IBioTMLFeatureColumns<IBioTMLToken> getFeatureColumns(List<IBioTMLToken> tokens, IBioTMLFeatureGeneratorConfigurator configuration) throws BioTMLException;
	
	
	@SuppressWarnings("rawtypes")
	public IBioTMLFeatureColumns<IBioTMLAssociation> getEventFeatureColumns(List<IBioTMLToken> tokens, List<IBioTMLAssociation> associations, IBioTMLFeatureGeneratorConfigurator configuration) throws BioTMLException;
	/**
	 * 
	 * Method that cleans the allocated memory of this module.
	 * 
	 */
	public void cleanMemory();
	
}